import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useStore } from '../store/StoreContext'
import { formatPrice, imageFallback, productImage } from '../utils/storefront'

export default function Cart() {
  const { cart, subtotal, updateQuantity, removeFromCart, clearCart } = useStore()
  const shipping = subtotal >= 5000 ? 0 : 250
  if (!cart.length) return <div className="er-page"><div className="er-empty er-cart-empty"><ShoppingBag/><h1>Your cart is empty</h1><p>Add your favorite products and return when you are ready.</p><Link className="er-btn er-btn--dark" to="/shop">Continue shopping</Link></div></div>
  return <div className="er-cart-page"><section><div className="er-cart-title"><div><p className="er-kicker">Your selection</p><h1>Shopping cart</h1></div><button className="er-text-link" onClick={clearCart}>Clear cart</button></div><div className="er-cart-list">{cart.map((item) => <article className="er-cart-line" key={item.cartKey}><Link className="er-cart-line__image" to={`/product?id=${item.id}`}><img src={productImage(item)} alt={item.title} onError={imageFallback}/></Link><div className="er-cart-line__copy"><div><Link to={`/product?id=${item.id}`}><h2>{item.title}</h2></Link><p>{item.category} · Size {item.selectedSize}</p><strong>{formatPrice(item.price)}</strong></div><div className="er-cart-line__actions"><div className="er-quantity"><button onClick={() => updateQuantity(item.cartKey, item.quantity - 1)} aria-label="Decrease quantity"><Minus/></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.cartKey, item.quantity + 1)} aria-label="Increase quantity"><Plus/></button></div><button className="er-remove" onClick={() => removeFromCart(item.cartKey)}><Trash2/> Remove</button></div></div><strong className="er-cart-line__total">{formatPrice(item.price * item.quantity)}</strong></article>)}</div></section><aside className="er-summary"><p className="er-kicker">Order summary</p><h2>Summary</h2><label className="er-coupon"><input placeholder="Discount code"/><button onClick={() => alert('Demo code saved. Add a real promotion API for live discounts.')}>Apply</button></label><dl><div><dt>Subtotal</dt><dd>{formatPrice(subtotal)}</dd></div><div><dt>Shipping</dt><dd>{shipping ? formatPrice(shipping) : 'Free'}</dd></div><div className="er-summary__total"><dt>Total</dt><dd>{formatPrice(subtotal + shipping)}</dd></div></dl><Link className="er-btn er-btn--dark" to="/checkout">Proceed to checkout</Link><Link className="er-text-link" to="/shop">Continue shopping</Link><p className="er-summary__note">Taxes included. Secure browser-local demo checkout.</p></aside></div>
}

